---
title: "Review of Stata's `dyndoc`"
author: "Tomas Dvorak"
date: "August 17, 2017"
output: 
  html_document:
    theme: lumen
---

As a huge fan of Stata I was super-excited for [dynamic documents newly available](http://www.stata.com/new-in-stata/markdown/) in the latest [Stata 15](http://www.stata.com/new-in-stata/) release.  I played with the feature for the last few days, and can report that I was able to produce a decent looking markdown document using Stata. However, I also have to say that Stata's markdown falls short of its [RMarkdown](http://rmarkdown.rstudio.com/) alternative. Here are the reasons:

1. Stata's dynamic document, `dyndoc`, is not integrated into Stata's development environment.  I typed [my dyndoc](https://github.com/dvorakt/TIER_exercises/blob/master/dyndoc_debt_growth/debt%20and%20growth%20stata%20dyndoc.do) using Stata's do-file editor. However, instead of pushing the execute button (as I would do, if I were to run a do-file), I had to go back to Stata's command line and type and execute `dyndoc` command. 

2. Stata's do-file editor is not built to handle dyndoc documents. Do-file editor treats everything as Stata code. This is good for my the *code* part of the document (code-chunks), but it is not good for the *text* part of the document. Do-file editor does not have spell check. It does not even recognize the dyndoc tags, i.e. it does not help with closing of the tags.

3. Some of the dyndoc tags are clumsy. For example, the start and end of a code-chunk use two lines each; including graphs requires one code-chunk to create a graph, and another code-chunk to include it into the document.  

4. Dyndoc does not produce pdf. There a separate command, [`putpdf`](http://www.stata.com/new-in-stata/create-pdfs/), which uses completely different markup language. This is in sharp contrast to the ability of RMarkdown to create html, pdf or word.

5. Dyndoc does not support LaTex, BibTex or even outreg. This alone will be a deal-breaker for many users. Outreg is super-popular for displaying regression results but, because it generates a separate file, I was not able to include it in the dyndoc. LaTex and BibTex users should probably check out [texdoc](http://repec.sowi.unibe.ch/stata/texdoc/) before trying out dyndoc.

6. Dyndoc does not support for publishing html to the web.  Stata's `dyndoc` lacks the one-button experience of publishing html that exists in [RStudio](https://www.rstudio.com/). Moreover, the html created by `dyndoc` is not self-contained (it needs any image/figure files). This makes sharing the document cumbersome, unlike the self-contained html created by RMarkdown. 

7. Dyndoc does not support code-folding, table of contents or themes. This is mostly aesthetic, and one can certainly customize the css included in the `dyndoc`'s html, but RMarkdown makes creating slick looking documents very easy. You can see `dyndoc`'s html [here](https://dvorakt.github.io/TIER_exercises/dyndoc_debt_growth/debt%20and%20growth%20stata%20dyndoc.html) (dyndoc source code [here](https://github.com/dvorakt/TIER_exercises/blob/master/dyndoc_debt_growth/debt%20and%20growth%20stata%20dyndoc.do)). For comparison, RMarkdown is [here](https://dvorakt.github.io/TIER_exercises/rmarkdown_debt_growth/debt_and_growth_R_Markdown.html) (source code [here](https://github.com/dvorakt/TIER_exercises/blob/master/rmarkdown_debt_growth/debt%20and%20growth%20R%20Markdown.Rmd)).

In conclusion, `dyndoc` is a tiny step in the right direction for Stata.  Much more needs to be done to be even in the neighborhood of the flexibility, capability and the ease of use of RMarkdown. 



